// Generated by CoffeeScript 1.7.1
'use strict';
var app;

app = angular.module('listfeature', ['ngRoute', 'ngSanitize', 'listControllers', 'listDirectives', 'ui.utils', 'duScroll']);

app.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/lists', {
      templateUrl: 'partials/list.html',
      controller: 'ListListCtrl'
    }).when('/lists/:listId', {
      templateUrl: 'partials/detail.html',
      controller: 'ListDetailCtrl'
    }).otherwise({
      redirectTo: '/lists'
    });
  }
]);
